on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: "go.mod"
      - name: Lint
        uses: golangci/golangci-lint-action@v6.2.0
      - name: Run unit tests
        run: go test ./...
